// Generates components/icons.tsx from the reicon outline set.
// Re-run with: bun scripts/build-icons.ts
import { readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"

const SRC = "/Users/safi/Documents/Cowork/Content/reicon-icons/outline"

// app name -> reicon file name
const ICONS: Record<string, string> = {
  archive: "archive", arrowDown: "arrow-down", arrowLeft: "arrow-left", arrowRight: "arrow-right",
  book: "book", branch: "branch-up", check: "check", chevronDown: "chevron-down",
  chevronRight: "chevron-right", clock: "clock", close: "x", command: "command",
  copy: "copy", edit: "edit-22", eye: "eye", eyeOff: "eye-off", file: "file",
  folder: "folder", home: "home", info: "info-circle", link: "link",
  loader: "loader", logout: "logout", menu: "menu", moon: "moon", more: "more-h",
  plus: "plus", refresh: "refresh", repo: "code-square", search: "search",
  settings: "setting2", sun: "sun", tip: "bulb", trash: "trash", user: "user",
  warning: "triangle-warning", shieldCheck: "shield-check",
}

function toJsx(svg: string) {
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "")
  return (
    inner
      .replace(/\s+/g, " ")
      // Drop clip paths: the ids repeat across files and every clip in this
      // set is a full-size rect, so it changes nothing visually.
      .replace(/<defs>[\s\S]*?<\/defs>/g, "")
      .replace(/\s*clip-path="url\([^)]*\)"/g, "")
      // Normalise every leaf element to a self-closing JSX tag.
      .replace(
        /<(path|polyline|line|rect|circle|ellipse|polygon)([^>]*?)\s*\/?>/g,
        "<$1$2 />",
      )
      .replace(/<\/(path|polyline|line|rect|circle|ellipse|polygon)>/g, "")
      .replace(/#000000/g, "currentColor")
      .replace(/fill-rule=/g, "fillRule=")
      .replace(/clip-rule=/g, "clipRule=")
      .replace(/stroke-width=/g, "strokeWidth=")
      .replace(/stroke-linecap=/g, "strokeLinecap=")
      .replace(/stroke-linejoin=/g, "strokeLinejoin=")
      .replace(/stroke-miterlimit=/g, "strokeMiterlimit=")
      .replace(/\s+/g, " ")
      .trim()
  )
}

const parts: string[] = [
  "// Generated by scripts/build-icons.ts. Do not edit by hand.",
  "// Source: reicon-icons outline set, 24px grid, currentColor.",
  'import type { SVGProps } from "react"',
  "",
  "export type IconProps = SVGProps<SVGSVGElement> & { size?: number }",
  "",
  "function svgProps({ size = 16, ...rest }: IconProps) {",
  '  return { width: size, height: size, viewBox: "0 0 24 24", fill: "none",',
  '    xmlns: "http://www.w3.org/2000/svg", "aria-hidden": true, ...rest }',
  "}",
  "",
]

for (const [name, file] of Object.entries(ICONS)) {
  const raw = readFileSync(join(SRC, `${file}.svg`), "utf8")
  const comp = name.charAt(0).toUpperCase() + name.slice(1)
  parts.push(
    `export function Icon${comp}(props: IconProps) {`,
    `  return <svg {...svgProps(props)}>${toJsx(raw)}</svg>`,
    "}",
    "",
  )
}

writeFileSync("components/icons.tsx", parts.join("\n"))
console.log(`wrote components/icons.tsx with ${Object.keys(ICONS).length} icons`)
